# Created by Jekyll Writer
title: 撩课-王顺子
author: Like-Sz
description: Python课程笔记
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: Sz
github_username: wangshunzi
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: /python
